#! /usr/bin/env python3

import argparse, threading, sys, tempfile, os
from json import load
from subprocess import Popen, PIPE
import subprocess


def threader(to_fetch, mach_djson, hidden):
    """Use multithreading to grab contents of files."""
    threads = [threading.Thread(target=fetch_data, args=(to_fetch[d], d, mach_djson, hidden)) for d in to_fetch]
    for thread in threads:
        thread.start()
    for thread in threads:
        thread.join()

def fetch_data(loc, dname, out_dict, hidden):
    """Loads a dataset.json file and saves its contents to out_dict; records hidden datasets."""
    with open(loc, "r") as f:
        djson = load(f)
    out_dict[dname] = djson
    if 'hide' in djson.values():
        hidden.add(dname)

def print_diffs(key, mach1_name, mach1_val, mach2_name, mach2_val):
    """Print out values that differ between two machines."""
    print(key, "\n", mach1_name + ": ", mach1_val, "\n", mach2_name + ": ", mach2_val)

def process_dict(mach1_name, mach1_dict, mach2_name, mach2_dict):
    """Processes a dictionary, printing out differing values if needed."""
    for key in mach1_dict.keys():
        mach1_val = mach1_dict[key]
        mach2_val = mach2_dict[key]
        if isinstance(mach1_val, dict):
            process_dict(mach1_name, mach1_val, mach2_name, mach2_val)
        else:
            if mach1_val != mach2_val:
                print_diffs(key, mach1_name, mach1_val, mach2_name, mach2_val)

def compare_machines(mach1_dict, mach1_name, mach2_dict, mach2_name, verbose=False):
    """
    Prints datasets that differ between two machines. Highlights datasets that
    exist on one machine but not the other. Verbose mode prints field-level diffs.
    """
    print(f'\nDatasets with diffs between {mach1_name} + {mach2_name}:')

    # Sort the datasets alphabetically
    sorted_datasets = sorted(mach2_dict.keys())

    for dataset in sorted_datasets:
        try:
            if mach1_dict[dataset] != mach2_dict[dataset]:
                print(dataset)
                if verbose:
                    for key in mach2_dict[dataset].keys():
                        if isinstance(mach2_dict[dataset][key], dict):
                            process_dict(mach2_name, mach2_dict[dataset][key], mach1_name, mach1_dict[dataset][key])
                        else:
                            try:
                                val1 = mach1_dict[dataset][key]
                                val2 = mach2_dict[dataset][key]
                                if val1 != val2:
                                    if key == "metaFields":
                                        print(key, mach1_name + " and " + mach2_name + " differ")
                                    else:
                                        print_diffs(key, mach2_name, val2, mach1_name, val1)
                            except KeyError:
                                print(key, f'present on {mach1_name}, but not on {mach2_name} or vice versa')
        except KeyError:
            print(dataset, f'present on {mach1_name}, but not on {mach2_name} or vice versa')


parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description="Shows diffs between cells-test and cells-beta. By default shows only names.")
parser.add_argument("-r", "--run", action='store_true',
    help='run script to look for diffs')
parser.add_argument("-s", "--stats", action='store_true',
    help='print stats about the number of datasets/collections on each machine')
parser.add_argument("-d", "--hidden", action='store_true',
    help='print datasets that are hidden on each machine')
parser.add_argument("-v", "--verbose", action='store_true',
    help='print field-level diffs for datasets that differ')
args = parser.parse_args()


def main():
    if not args.run:
        parser.print_help(sys.stderr)
        exit(1)

    ct_hide = set()
    ct_djson = dict()
    ct_loc = dict()
    ct_base = "/usr/local/apache/htdocs-cells/"
    bash_cmd = 'find ' + ct_base + ' -name dataset.json | cut -f6- -d "/" | sed "s/\/dataset.json//g" | sort'
    p = Popen([bash_cmd], shell=True, stdout=PIPE, stderr=PIPE)
    cmdout, cmderr = p.communicate()
    ct_datasets = set(cmdout.decode().strip().split('\n'))
    ct_datasets.remove('dataset.json')
    for dname in ct_datasets:
        ct_loc[dname] = ct_base + dname + "/dataset.json"
    threader(ct_loc, ct_djson, ct_hide)

    cb_hide = set()
    cb_djson = dict()
    cb_loc = dict()
    cb_base = '/usr/local/apache/htdocs-cells-beta/'
    bash_cmd = 'find ' + cb_base + ' -name dataset.json | cut -f6- -d "/" | sed "s/\/dataset.json//g" | sort'
    p = Popen([bash_cmd], shell=True, stdout=PIPE, stderr=PIPE)
    cmdout, cmderr = p.communicate()
    cb_datasets = set(cmdout.decode().strip().split('\n'))
    cb_datasets.remove('dataset.json')
    for dname in cb_datasets:
        cb_loc[dname] = cb_base + dname + "/dataset.json"
    threader(cb_loc, cb_djson, cb_hide)

    rr_hide = set()
    rr_djson = dict()
    rr_datasets = set()
    rr_paths = dict()
    cmd = ['ssh', 'qateam@hgw0.soe.ucsc.edu', 'find', ct_base, '-name',
        'dataset.json', '|', 'cut', '-f', '6-', '-d', '"/"']
    p = Popen(cmd, shell=False, stdout=PIPE, stderr=PIPE)
    cmdout, cmderr = p.communicate()
    rr_files = set(cmdout.decode().rstrip().split('\n'))

    with tempfile.NamedTemporaryFile(prefix='cb_', delete=False) as tmp:
        tmp.write(cmdout)
        tmp.flush()
        tmp_name = tmp.name

    rr_base = '/data/tmp/cb_tmp_new'
    os.makedirs(rr_base, exist_ok=True)
    rsync_cmd = ['rsync', '--files-from=' + tmp_name,
        'qateam@hgw0.soe.ucsc.edu:/usr/local/apache/htdocs-cells/', rr_base]
    print("running ", rsync_cmd)
    subprocess.run(rsync_cmd, check=True)
    os.unlink(tmp_name)

    for fname in rr_files:
        fsplit = fname.strip().split('/')
        dname = '/'.join(fsplit[:-1])
        if dname != '':
            dpath = rr_base + '/' + dname + '/dataset.json'
            rr_paths[dname] = dpath
            rr_datasets.add(dname)
    threader(rr_paths, rr_djson, rr_hide)

    if args.hidden:
        if ct_hide:
            print("cells-test hidden datasets:")
            for dataset in sorted(ct_hide):
                print(dataset)
            print("\n")
        if cb_hide:
            print("cells-beta hidden datasets:")
            for dataset in sorted(cb_hide):
                print(dataset)
            print("\n")
        if rr_hide:
            print("cells hidden datasets:")
            for dataset in sorted(rr_hide):
                print(dataset)
            print("\n")

    dev_only = sorted(x for x in ct_datasets.difference(cb_datasets) if "/" not in x)
    if dev_only:
        print("Datasets on cells-test only:")
        for dataset in dev_only:
            print(dataset)
        print("\n")

    beta_only = sorted(x for x in cb_datasets.difference(rr_datasets) if "/" not in x)
    if beta_only:
        print("Datasets on cells-beta, but not on RR:")
        for dataset in beta_only:
            print(dataset)
        print("\n")

    compare_machines(ct_djson, "cells-test", cb_djson, "cells-beta", args.verbose)
    compare_machines(cb_djson, "cells-beta", rr_djson, "cells", args.verbose)

    ct_top = set(x for x in ct_datasets if "/" not in x)
    cb_top = set(x for x in cb_datasets if "/" not in x)
    rr_top = set(x for x in rr_datasets if "/" not in x)

    if args.stats:
        print("Num of top-level datasets/collections")
        print("\tcells-test:", len(ct_top))
        print("\tcells-beta:", len(cb_top))
        print("\tcells:", len(rr_top))
        print("Num of datasets (including those in collections):")
        print("\tcells-test:", len(ct_datasets))
        print("\tcells-beta:", len(cb_datasets))
        print("\tcells:", len(rr_datasets))


if __name__ == "__main__":
    main()
