#! /usr/bin/env python3

import sys, argparse, re, json, operator
from collections import OrderedDict
from os.path import join, basename, dirname, isfile
from pathlib import Path

# These two functions copied and modified from cellbrowser.py
def readLines(lines, fname):
    "recursively read lines from fname"
    with open(fname) as f:
        for line in f:
            lines.append(line.rstrip("\r\n"))
    return lines

def loadConfig(fname):
    """ parse python in fname and return variables as dictionary. """
    if fname.endswith(".json"):
        with open(fname) as f:
            return json.load(f)

    conf = OrderedDict()
    g = {}
    g["fileBase"] = basename(fname).split('.')[0]
    g["dirName"] = basename(dirname(fname))
    lines = readLines([], fname)
    exec("\n".join(lines), g, conf)
    return conf

def main():
    # Set up script arguments
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Get all values for a list of datasets for specified cellbrowser.conf tag")
    parser.add_argument('datasetFile', type=str, help='file containing list of datasets in first column')
    parser.add_argument('tag', type=str, help='cellbrowser.conf tag you want values for, e.g. body_parts')
    parser.add_argument('-d', '--descConf', action='store_true', help='search for tag in desc.conf instead of cellbrowser.conf')
    parser.add_argument('-j', '--json', action='store_true', help='search for tag in dataset.json in apache htdocs directory instead of cellbrowser.conf')
    parser.add_argument('-s', '--sort', action='store_true', help='sort results')
    parser.add_argument('-k', '--sortField', action='store', help='name of field to sort on')
    args = parser.parse_args()

    dFtype = Path(args.datasetFile).suffix

    if dFtype == ".csv":
        dsep = ","
    elif dFtype == ".tsv":
        dsep = "\t"
    else:
        print("datasetFile must have tsv or csv file extension")
        exit(1)

    if "," in args.tag:
        tags = args.tag.split(",")
    else:
        tags = args.tag.split()
    tagIndex = dict()

    with open(args.datasetFile) as dfh:
        header = dfh.readline().rstrip().split(dsep)
        if not header[0].startswith("#"):
            print("First line needs to be a header line with column names and must start with '#'")
            exit(1)

        for tag in tags:
            try:
                n = header.index(tag)
                tagIndex[tag] = n
            except ValueError:
                header.append(tag)
                n = header.index(tag)
                tagIndex[tag] = n
        print(*header, sep=dsep)

        outRows = []
        for line in dfh:
            if not line.startswith('#'):
                splitLine = line.rstrip().split(dsep)
                dname = splitLine[0]

                if args.descConf:
                    confName = join("/hive/data/inside/cells/datasets", dname, "desc.conf")
                elif args.json:
                    confName = join("/usr/local/apache/htdocs-cells/", dname, "dataset.json")
                else:
                    confName = join("/hive/data/inside/cells/datasets", dname, "cellbrowser.conf")

                if isfile(confName):
                    conf = loadConfig(confName)
                    for tag in tagIndex:
                        n = tagIndex[tag]
                        if tag in conf:
                            tagVal = str(conf[tag])
                            tagVal = re.sub('[\[\]\'"]', '', tagVal)
                            if n <= len(splitLine) - 1:
                                splitLine[n] = tagVal
                            else:
                                splitLine.append(tagVal)
                        else:
                            splitLine.append("")
                    outRows.append(splitLine)
                else:
                    sys.stderr.write('Warning: "' + dname + '" does not have a cellbrowser.conf and/or desc.conf. You might want to double check your input file.\n')

    if args.sort:
        if args.sortField:
            sortIdx = tagIndex[args.sortField]
            outRows.sort(key=operator.itemgetter(sortIdx))
        else:
            outRows.sort()

    for row in outRows:
        print(*row, sep='\t')

if __name__ == "__main__":
    main()
