#!/usr/bin/env python3

import sys
import argparse
import logging
import collections
import operator
import contextlib

parser = argparse.ArgumentParser(
    description="Print lines where a value occurs in a certain column for the first time; skip duplicates. Ignores comment lines starting with #.",
    usage="%(prog)s [options] filename ...")

parser.add_argument("-d", "--debug", dest="debug", action="store_true", help="show debug messages")
parser.add_argument("-c", "--count", dest="count", action="store_true", help="add count")
parser.add_argument("-s", "--sort", dest="sort", action="store_true", help="add count and sort")
parser.add_argument("-S", "--sortRev", dest="sortRev", action="store_true", help="add count and reverse-sort")
parser.add_argument("-r", "--ratio", dest="ratio", action="store_true", help="add count and ratio and sort")
parser.add_argument("--minCount", dest="minCount", type=int, default=None,
    help="output only with at least these many counts")
parser.add_argument("--maxCount", dest="maxCount", type=int, default=None,
    help="output only with no more than these many counts")
parser.add_argument("-k", "--colIndex", dest="colIndex", action="append", type=int, default=None,
    help="index of column(s) to use, zero-based, can be used multiple times")
parser.add_argument("-n", "--colName", dest="colNames", action="append", default=None,
    help="name of column(s) to use, can be used multiple times")
parser.add_argument("-a", "--appendLines", dest="appendLines", action="store_true",
    help="if both -s and -k are set: show fields from -k and counts from -s, and also append complete lines separated by |")
parser.add_argument("filenames", nargs="*")

args = parser.parse_args()

if args.debug:
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.INFO)

filenames = args.filenames
fromStdin = False
if len(filenames) == 0:
    filenames = ["stdin"]
    fromStdin = True

colIndexLst = None
if args.colNames is not None:
    if fromStdin:
        line1 = sys.stdin.readline().rstrip("\n")
    else:
        with open(filenames[0]) as f:
            line1 = f.readline().rstrip("\n")
    headers = line1.split("\t")
    nameToCol = {name: i for i, name in enumerate(headers)}
    colIndexLst = [nameToCol[n] for n in args.colNames]
elif args.colIndex is not None:
    colIndexLst = args.colIndex

fullLines = collections.defaultdict(list)
values = collections.defaultdict(int)
lineCount = 0

for filename in filenames:
    ctx = contextlib.nullcontext(sys.stdin) if filename == "stdin" else open(filename)
    with ctx as ifh:
        for line in ifh:
            if line.startswith("#"):
                continue
            lineCount += 1
            fields = line.rstrip("\n").split("\t")
            if colIndexLst is None:
                valueTuple = tuple(fields)
            else:
                valueTuple = tuple(fields[x] for x in colIndexLst)
                fullLines[valueTuple].append(line.rstrip("\n"))
            values[valueTuple] += 1

values = list(values.items())

if args.sort or args.ratio:
    values.sort(key=operator.itemgetter(-1))
if args.sortRev:
    values.sort(key=operator.itemgetter(-1), reverse=True)

for key, count in values:
    row = list(key)
    if args.count or args.sort or args.ratio or args.sortRev:
        row.append(str(count))
        if args.ratio:
            row.append("%0.3f%%" % (100 * float(count) / lineCount))
        elif colIndexLst and args.appendLines:
            row.append("|".join(fullLines[key]))
    elif colIndexLst:
        row = fullLines[key]

    if (args.maxCount is None or count < args.maxCount) \
            and (args.minCount is None or count > args.minCount):
        print("\t".join(row))
