#! /usr/bin/env python3

import json, sys, operator, argparse, os, urllib.request, subprocess, time, glob
from datetime import datetime, timedelta, date
from collections import defaultdict

parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description="Update 'News' section in desc.conf. Also updates sitemap and list of datasets currently on the RR.")
parser.add_argument("-r","--run", action='store_true',
    help='run script to update news, rr datasets list, and sitemap.')
parser.add_argument("--newsOnly", action='store_true',
    help='only update news html')
parser.add_argument("-n","--now", action='store_true',
    help='set release date for current directory to Monday of this week')
parser.add_argument("-p","--perDateDir", action='store', default="/hive/data/inside/cells/news/perDate/",
    help='where to find perDate news file')
parser.add_argument("-o","--newsOutDir", action='store', default="/hive/data/inside/cells/news/",
    help='where to output news file')
parser.add_argument("-d","--rrDatasetsOut", action='store', default="/hive/data/inside/cells/",
    help='directory where to find/output rr.datasets.txt')
parser.add_argument("-s","--sitemap", action='store', default="/hive/data/inside/cells/",
    help='directory where to output sitemap file')
parser.add_argument("-j","--dateJson", action='store', default="/hive/data/inside/cells/news/",
    help='directory where to output releaseDate.json file')
args = parser.parse_args()


def buildSitemapSet():
    """Builds a set of all URLs currently in the sitemap."""

    sitemapPath = args.sitemap + "/sitemap.cells.txt"
    sitemapSet = set()

    # If the sitemap file exists, then open it and add each line to a new set
    if os.path.exists(sitemapPath):
        sitemap = open(sitemapPath, "r")
        for line in sitemap:
            sitemapSet.add(line)
        sitemap.close()
    # Otherwise, just make an empty file?
    # Maybe I should try/except here instead?
    else:
        sitemap = open(sitemapPath, "w")
        sitemap.close()

    return sitemapSet

def addSiteToSitemap(entry, sitemapSet):
    """Writes an entry out to the sitemap if it's not already there."""

    # Open sitemap file
    with open(args.sitemap + "/sitemap.cells.txt", "a") as sitemap:
        urlline = "https://" + entry + ".cells.ucsc.edu\n"
        if urlline not in sitemapSet:
            sitemap.write(urlline)

def makeDate(aDate):
    """Will turn a string date separated by "-" into a date object."""

    #if aDate
    # to make a date object, we need at least the year, month, and day
    splitDate = aDate.split("-")
    year = int(splitDate[0])
    month = int(splitDate[1])
    day = int(splitDate[2])
    dateObj = date(year, month, day)

    return dateObj

def mondayBefore(aDate):
    """Returns the date of the monday before a given date."""

    # Use makeDate function to make input date into a datetime object
    dateObj = makeDate(str(aDate))
    # From https://www.programiz.com/python-programming/datetime
    # Basically allows us to get the date for the monday in which
    # a given date falls
    monday = dateObj - timedelta(days=dateObj.weekday())

    return monday

def jsonListsToSets(o):
    """converts lists in input json to sets"""
    # from:
    # https://stackoverflow.com/questions/39787795/how-to-convert-all-lists-to-sets-when-json-file-is-loaded
    if isinstance(o, list):
        return {jsonListsToSets(v) for v in o}
    elif isinstance(o, dict):
        return {k: jsonListsToSets(v) for k, v in o.items()}
    return o

def parseDateJson(dateJson):
    """Load releaseDate.json file"""
    with open(dateJson, 'r') as f:
        dateJson = json.load(f)

    dateDict = jsonListsToSets(dateJson)

    return dateDict

def dumpToJson(data, outputFile):
    """output data to named outputFile"""
    jsonFile = open(outputFile, "w")
    # code snippet from Google AI
    jsonOut = json.dumps({k: list(v) if isinstance(v, set) else v for k, v in data.items()}, indent=2, sort_keys=True)
    jsonFile.write(jsonOut)
    jsonFile.close()

def processDataset(dataset, rootDir):
    """Processes a single dataset and returns the shortname and a list of info about that dataset."""

    name = dataset["name"]
    # 'firstBuildTime was added by Max in early 2022, so not all datasets have it
    # Need to be resistant to it not being there
    try:
        lastmtime = dataset["firstBuildTime"]
    except KeyError:
        lastmtime = time.strftime('%Y-%m-%d', time.localtime(os.path.getmtime(os.path.join(rootDir, name, "exprMatrix.bin"))))
    monday = mondayBefore(lastmtime)

    # Collect info for dataset to return at end of function
    short = dataset["shortLabel"]
    count = str(dataset["sampleCount"])
    dList = [short, count, monday]

    return name, dList

def processCollection(collection, rootDir):
    """Processes a collection and returns a list of info about that collection.
       If it runs into a nested collection, will also process that."""

    collInfo = list()

    name = collection["name"]
    cjson = json.load(open(os.path.join(rootDir, name, "dataset.json"), "r"))
    subdirs = cjson["datasets"]

    for sub in subdirs:
        if 'isCollection' in sub.keys():
            # If we run into another collection, process it in the same way
            subCollInfo = processCollection(sub, rootDir)
            # Need to do this appending here otherwise subcollection info disappears
            collInfo = collInfo + subCollInfo

        else:
            # Otherwise, process each dataset in a collection as a normal dataset
            subInfo = processDataset(sub, rootDir)
            subDict = {subInfo[0]:subInfo[1]}
            collInfo.append(subDict)

    return collInfo

def parseBetaDatasets():
    """Parses dataset.json for cells-beta to get a current list of datasets."""

    # Builds dictionary of datasets currently on the beta, assuming it's a proxy of the RR
    betaInfo = dict() # a smaller dict that contains only name/shortLabel/count/release date
    bdir = "/usr/local/apache/htdocs-cells-beta/"
    cellsBeta =  json.load(open(os.path.join(bdir, "dataset.json"), "r"))
    for dataset in cellsBeta["datasets"]:
        if "isCollection" in dataset.keys():
            collectionInfo = processCollection(dataset, bdir)
            cname = dataset["name"]
            cshort = dataset["shortLabel"]

            oldDate = date.today()
            collCellCount = 0
            # After we process the collection, we want to add the info for that
            # to the betaInfo dictionary
            for d in collectionInfo:
                dname = list(d.keys())[0]
                info = d[dname]
                betaInfo[dname] = info

                collCellCount += int(info[1])
                day = info[2]
                # Do some comparison to see if data for current dataset in collection
                # is older than the last
                if day < oldDate:
                    oldDate = day
            # Also add an entry to betaInfo that covers the collection as a whole
            # Cell count for this one is the sum of the cell counts for all subdatasets
            # Date is that for the oldest dataset in the collection
            betaInfo[cname] = [cshort, str(collCellCount), oldDate]
        else:
            dname, bList = processDataset(dataset, bdir)
            betaInfo[dname] = bList

    return betaInfo

def combineNews():
    """ Combines all of the perDate files into a single html file"""

    # From https://stackoverflow.com/questions/3207219/how-do-i-list-all-files-of-a-directory
    newsFiles = sorted(glob.glob(args.perDateDir+"*.html"), reverse=True)
    # Basically, we're gathering up all of the individual news files to combine them into one
    basicNews = args.newsOutDir + "/basic.html"
    filenames = [basicNews] + newsFiles
    outName = os.path.join(args.newsOutDir, 'combined.html')
    with open(outName, 'w') as outfile:
        for fname in filenames:
            with open(fname) as infile:
                outfile.write(infile.read())

def writeNewsHtml(toPrint, dateDir):
    """Takes a list of datasets and writes out an html file per day that lists
       all datasets released that day."""

    for day in toPrint:
        dateOut = dateDir + str(day) + ".html"
        htmlOut = open(dateOut, "w")

        # Do some work to get the date into something we can easily grab pieces of
        betterDate = time.strftime('%d-%b-%Y', day.timetuple())
        splitDay = betterDate.split("-")
        # Separate vars for month/day/year
        month=splitDay[1]
        dayNum=splitDay[0]
        year=splitDay[2]

        # Write bits out to the news file for the specific day
        htmlOut.write("<p><b>" + month + " " + dayNum + ", " + year + "</b></p>\n")
        htmlOut.write("<p>New datasets:</p>\n<ul>\n")
        for line in toPrint[day]:
            htmlOut.write(line)
        htmlOut.write("</ul>\n")
        htmlOut.close()

def main():
    if args.run == True:
        # From https://stackoverflow.com/questions/19216334/python-give-start-and-end-of-week-data-from-a-given-date
        # and https://www.programiz.com/python-programming/datetime/current-datetime
        # Get date for Monday, so that all datasets added in the last week show up under the same date
        start = mondayBefore(date.today().strftime('%Y-%m-%d'))

        # File should contain RR datasets
        # First run of this script will generate this file,
        # move it out of the way to regenerate, though this means that
        # everything will be noted as being released on the same day
        rrDatasetsPath = os.path.join(args.rrDatasetsOut, "rr.datasets.txt")
        dateDir = args.perDateDir

        sitemapSet = buildSitemapSet()

        dateJsonFile = os.path.join(args.dateJson, "releaseDate.json")
        if os.path.exists(dateJsonFile):
            dateDict = parseDateJson(dateJsonFile)
        else:
            dateDict = defaultdict(set)
            # ex entry: {"2021-01-01":{cortex-dev, neuro-degen-atac}}

        # This should only happen if this is the first time the script is run
        # or if previous version is moved/deleted
        if not os.path.exists(rrDatasetsPath):
            with open(rrDatasetsPath, "a") as rrDatasets:
                rrDatasets.write("#release_date\tdataset_shortname\tdataset_label\tcell_count")
            betaInfo = parseBetaDatasets()
            toPrint = dict()
            for entry in betaInfo.keys():
                # triggers if run in a dataset directory with "-now" argument
                if entry == os.path.basename(os.getcwd()) and args.now:
                    day = mondayBefore(date.today())
                    for d in dateDict.keys():
                        if entry in dateDict[d]:
                            oldDay = d
                            dateDict[oldDay].remove(entry)
                # triggers for other datasets and if dateDict (i.e. releaseDate.json) has an entry for a dataset
                elif entry in dateDict:
                    for d in dateDict.keys():
                        if entry in dateDict[d]:
                            day = d
                # Otherwise, use first creation time of dataset
                else:
                    day = betaInfo[entry][2]

                label = betaInfo[entry][0]
                count = betaInfo[entry][1]
                # construct line to output in rr.datasets.txt
                line = str(day) + "\t" + entry + "\t" + str(label) + "\t" + count + "\n"
                if not args.newsOnly:
                    with open(rrDatasetsPath, "a") as rrDatasets:
                        rrDatasets.write(line)
                # Check if '/' in shortname, if so means it's a dataset in a collection
                # and we're not outputting it to the sitemap or to the announcements
                if "/" not in entry:
                    if not args.newsOnly:
                        addSiteToSitemap(entry, sitemapSet)
                    dateDict[str(day)].add(entry)
                    outLine = "  <li><a href='?ds=" + entry + "' target='_blank'>" + label + "</a>\n"
                    if day not in toPrint.keys():
                        toPrint[day] = [outLine]
                    else:
                        toPrint[day].append(outLine)

            dumpToJson(dateDict, dateJsonFile)

            writeNewsHtml(toPrint, dateDir)
            combineNews()

        else: # This is the main part of the function that prints out the html for a news update
            betaInfo = parseBetaDatasets()

            # Parse the old rr.datasets.txt file so we know what's already out there
            oldNames = set()
            oldDatasets = open(rrDatasetsPath,"r")
            for line in oldDatasets:
                splitLine = line.strip().split("\t")
                name = splitLine[1]
                oldNames.add(name)
            oldDatasets.close()

            # from here the code is mostly the same as that under the 'if' section above
            # should probably figure out a way to de-duplicate some of this?
            sitemapSet = buildSitemapSet()

            allDatasets = open(rrDatasetsPath,"a")
            # Go through and determine which datasets need to be added to the news announcements
            toPrint = dict()
            for entry in betaInfo:
                if entry == os.path.basename(os.getcwd()) and args.now:
                    day = mondayBefore(date.today())
                    for d in dateDict.keys():
                        if entry in dateDict[d]:
                            oldDay = d
                            dateDict[oldDay].remove(entry)
                # will trigger if dataset is already in our releaseDate,json, but we're not replacing the date
                elif entry in dateDict:
                    for d in dateDict.keys():
                        if entry in dateDict[d]:
                            day = d
                else:
                    day = betaInfo[entry][2]
                label = betaInfo[entry][0]
                count = betaInfo[entry][1]
                line = str(day) + "\t" + entry + "\t" + str(label) + "\t" + count + "\n"
                if not args.newsOnly:
                    if entry not in oldNames:
                        allDatasets.write(line)
                # Check if '/' in shortname, if so means it's a dataset in a collection
                # and we're not outputting it to the sitemap or to the announcements
                if "/" not in entry:
                    if not args.newsOnly:
                        addSiteToSitemap(entry, sitemapSet)
                    dateDict[str(day)].add(entry)
                    #try:
                    #    dateDict[str(day)].add(entry)
                    #except KeyError:
                    #    dateDict[str(day)] = {entry}
                    outLine = "  <li><a href='?ds=" + entry + "' target='_blank'>" + label + "</a>\n"
                    # If doesn't already in exist in toPrint, add it
                    if day not in toPrint.keys():
                        toPrint[day] = [outLine]
                    else:
                        toPrint[day].append(outLine)

            dumpToJson(dateDict, dateJsonFile)

            # Print out HTML for new datasets to be put into /hive/data/inside/cells/datasets/desc.conf
            writeNewsHtml(toPrint, dateDir)
            combineNews()

    else:
        parser.print_help(sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
